/**
 * 帮助文本（Markdown 格式，直接当作 done 状态卡片正文）
 */
export function helpMarkdown(): string {
  return [
    '**🤖 lark-kiro-bridge** — 在飞书里调用本地 Kiro CLI',
    '',
    '**会话**',
    '`/new` 或 `/reset` — 重置当前会话',
    '`/status` — 查看 cwd / session / 工作区 / watchdog',
    '`/stop` — 停止正在跑的任务',
    '',
    '**工作目录**',
    '`/cd <path>` — 切换到指定目录（必须在白名单内）',
    '`/pwd` — 查看当前目录',
    '',
    '**命名工作区**',
    '`/ws list` — 列出所有命名工作区',
    '`/ws save <name>` — 把当前 cwd 存为工作区',
    '`/ws use <name>` — 切到命名工作区',
    '`/ws remove <name>` — 删除工作区',
    '',
    '**运维**',
    '`/timeout [N|off|default]` — idle watchdog 阈值（分钟）',
    '`/model [name|auto]` — 查看 / 切换 / 重置模型（kiro 引擎）',
    '`/runtime [kiro|cursor]` — 查看 / 切换 Agent CLI 引擎（kiro-cli-acp / cursor-agent-cli）',
    '`/config` — 查看 / 编辑访问控制 + 偏好（管理员）',
    '`/steering [list|view|edit|new|rm] [--global]` — 管理 Kiro steering 文件',
    '`/cron [list|add|rm|pause|resume|run|next|translate]` — 定时任务',
    '`/ps` — 列出本机所有 bridge 进程',
    '`/exit <id>` — 停止指定进程（管理员）',
    '`/reconnect` — 重连飞书 WebSocket',
    '`/doctor [描述]` — 让 Kiro 看日志自诊断',
    '',
    '**其他**',
    '`/help` — 显示这条帮助',
    '其他斜杠命令会被原样转发给 Kiro（你可以自己定义）',
    '⚠️ kiro-cli 内置 TUI 命令（`/agent` `/tools` `/compact` `/login` `/logout`）在非交互模式下不可用',
    '',
    '**直接发文字** — 转发给 Kiro CLI 当作问题处理。',
    '**发图片或文件** — 自动下载到本地，把路径喂给 Kiro。',
    '群里需要 @机器人 才会响应；私聊任何消息都会触发。',
  ].join('\n');
}
